apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: hanhailin/topologic 
        #livenessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 5
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
